// <auto-generated />
using System;
using DentalManagerAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentalManagerAPI.Migrations
{
    [DbContext(typeof(DentalManagerDBContext))]
    [Migration("20220203220151_rename-columnid")]
    partial class renamecolumnid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Ukrainian_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DentalManagerAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "test",
                            DateOfBirth = new DateTime(2000, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ivan",
                            LastName = "Raikovskyi",
                            PhoneNumber = "+380673646192"
                        },
                        new
                        {
                            Id = 2,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 3,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 4,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 5,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 6,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 7,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 8,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 9,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 10,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 11,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 12,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 13,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 14,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 15,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 16,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 17,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 18,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 19,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 20,
                            Address = "test2",
                            DateOfBirth = new DateTime(2001, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mykola",
                            LastName = "Harch",
                            PhoneNumber = "+380973656192"
                        },
                        new
                        {
                            Id = 21,
                            Address = "test3",
                            DateOfBirth = new DateTime(2002, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Maksym",
                            LastName = "Boiko",
                            PhoneNumber = "+380963386182"
                        });
                });

            modelBuilder.Entity("DentalManagerAPI.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("DentalManagerAPI.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("DentalManagerAPI.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "testadd",
                            Email = "test@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Raikovskyi",
                            Password = "test",
                            PhoneNumber = "+384613646192"
                        });
                });

            modelBuilder.Entity("DentalManagerAPI.Models.Service", b =>
                {
                    b.HasOne("DentalManagerAPI.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");
                });
#pragma warning restore 612, 618
        }
    }
}
